version: '3.8'

networks:
  sensor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  camera:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: camera
    ports:
      - "18554:8554"  # RTSP stream for camera
    devices:
      - "/dev/video0:/dev/video0"  # Pass the video device to the container
    hostname: camara-server
    networks:
      sensor-network:
        ipv4_address: 172.30.0.2
    volumes:
      - $PWD/mediamtx.yml:/mediamtx.yml
    environment:
      - RTSP_PORT=8554
      - MTX_PATH="camera"
      - MTX_PROTOCOLS=tcp,udp
